# .devcontainer/environment.yml
# Optimized for fast dependency resolution with Miniforge/mamba

name: upside2-env
channels:
  - conda-forge
  - defaults

dependencies:
  # --- Build tools ---
  # Installing these via conda ensures that packages requiring compilation
  # (like prody, mdtraj) have the correct C/C++ compilers and Python headers.
  - c-compiler
  - cxx-compiler
  - make

  # --- Core Python and Packages ---
  - python=3.11
  
  # --- Scientific Computing Stack ---
  # Updated numpy constraint for better compatibility with recent packages
  - numpy>=1.21,<1.26
  - scipy
  - pandas
  
  # --- HDF5 and related packages ---
  - pytables
  - h5py
  
  # --- Statistical and analysis packages ---
  # Note: pymbar not available for linux-aarch64, install via pip if needed
  # - pymbar
  
  # --- Project-specific dependencies ---
  # These are now installed directly from conda-forge for better compatibility
  - mdtraj
  - prody

  # --- Development and utility tools ---
  - setuptools
  - pip
  
  # --- Debugging and development tools ---
  - gdb
  - ccache
  - ipdb
  - pdbpp
  - line_profiler
  - memory_profiler
  - py-spy
  
  # --- Data science and visualization ---
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipywidgets
  - nglview
  
  # --- Pip section ---
  # Keep minimal; only for packages not available on conda-forge
  - pip: []
